# Generated by Django 3.0.3 on 2020-03-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='note_text',
            field=models.TextField(default=''),
        ),
    ]
