# Generated by Django 3.0.3 on 2020-04-02 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0004_auto_20200321_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
